# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# HAVE_POSIX_MEMALIGN_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_POSIX_MEMALIGN_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The HAVE_POSIX_MEMALIGN_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libpcl-1.7.2/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libpcl-1.7.2/CMakeFiles/cmTC_9f51b-HAVE_POSIX_MEMALIGN_EXITCODE
# Run arguments : 
#    Called from: [3]	/usr/local/share/cmake-3.8/Modules/CheckCXXSourceRuns.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libpcl-1.7.2/cmake/pcl_find_sse.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libpcl-1.7.2/CMakeLists.txt

set( HAVE_POSIX_MEMALIGN_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

