# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# CMAKE_REQUIRE_LARGE_FILE_SUPPORT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CMAKE_REQUIRE_LARGE_FILE_SUPPORT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_1c648-CMAKE_REQUIRE_LARGE_FILE_SUPPORT
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMake/CheckCXXSourceRuns.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeLists.txt

set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# VTK_TYPE_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_TYPE_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_TYPE_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMake/vtkTestCharSignedness.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_a8e06-VTK_TYPE_CHAR_IS_SIGNED
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMake/vtkTestTypes.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeLists.txt

set( VTK_TYPE_CHAR_IS_SIGNED 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)


# VTK_ANSI_STREAM_EOF_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_ANSI_STREAM_EOF_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_ANSI_STREAM_EOF_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMake/vtkTestStreamEOF.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_2a32e-VTK_ANSI_STREAM_EOF_RESULT
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMake/vtkTestStreamsLibrary.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeLists.txt

set( VTK_ANSI_STREAM_EOF_RESULT 
     "FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)


# KWSYS_LFS_WORKS
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_LFS_WORKS to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_LFS_WORKS__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_LFS_WORKS__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_LFS_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_837bd-KWSYS_LFS_WORKS
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTests.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTests.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/CMakeLists.txt

set( KWSYS_LFS_WORKS 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( KWSYS_LFS_WORKS__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# KWSYS_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_de5e9-KWSYS_CHAR_IS_SIGNED
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTests.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/kwsysPlatformTests.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/Utilities/KWSys/vtksys/CMakeLists.txt

set( KWSYS_CHAR_IS_SIGNED 
     "FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# TEST_LFS_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set TEST_LFS_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The TEST_LFS_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/HDF5Tests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_2e418-TEST_LFS_WORKS_RUN
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( TEST_LFS_WORKS_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# TEST_DIRECT_VFD_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set TEST_DIRECT_VFD_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# TEST_DIRECT_VFD_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set TEST_DIRECT_VFD_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The TEST_DIRECT_VFD_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/HDF5Tests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_910ab-TEST_DIRECT_VFD_WORKS_RUN
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( TEST_DIRECT_VFD_WORKS_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( TEST_DIRECT_VFD_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# HDF5_PRINTF_LL_TEST_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HDF5_PRINTF_LL_TEST_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HDF5_PRINTF_LL_TEST_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/HDF5Tests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_fe175-HDF5_PRINTF_LL_TEST_RUN
# Run arguments : 
#    Called from: [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( HDF5_PRINTF_LL_TEST_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT 
     "PRINTF_LL_WIDTH=[l]"
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_INTEGER_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_INTEGER_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_a829f-H5_LDOUBLE_TO_INTEGER_WORKS_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_LDOUBLE_TO_INTEGER_WORKS_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULONG_TO_FLOAT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULONG_TO_FLOAT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULONG_TO_FLOAT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_4a278-H5_ULONG_TO_FLOAT_ACCURATE_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_ULONG_TO_FLOAT_ACCURATE_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_99b52-H5_FP_TO_ULLONG_ACCURATE_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_FP_TO_ULLONG_ACCURATE_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_RIGHT_MAXIMUM_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_f144f-H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_UINT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_UINT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_951e4-H5_LDOUBLE_TO_UINT_ACCURATE_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_LDOUBLE_TO_UINT_ACCURATE_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULLONG_TO_LDOUBLE_PRECISION_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_81669-H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN 
     "FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_INTEGER_OVERFLOW_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_6440b-H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_LLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_c40de-H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LLONG_TO_LDOUBLE_CORRECT_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LLONG_TO_LDOUBLE_CORRECT_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_62a2c-H5_LLONG_TO_LDOUBLE_CORRECT_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_LLONG_TO_LDOUBLE_CORRECT_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_NO_ALIGNMENT_RESTRICTIONS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_NO_ALIGNMENT_RESTRICTIONS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConversionTests.c
# Executable    : /home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/CMakeFiles/cmTC_65cbf-H5_NO_ALIGNMENT_RESTRICTIONS_RUN
# Run arguments : 
#    Called from: [3]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [2]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	/home/daquitree/RKSDK/rk3326/buildroot/output/rockchip_rk3326_robot64/build/libvtk-v6.2.0/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

set( H5_NO_ALIGNMENT_RESTRICTIONS_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

